/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lots.mercurius.addLid;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lots.mercurius.stemming.Main;
import lots.mercurius.stemming.sqlHandler.SQLhandler;

/**
 *
 * @author joris
 */
public class AddLid extends javax.swing.JFrame {

    private Main main;
    private Calendar day = Calendar.getInstance(TimeZone.getTimeZone("Europe/Brussels"), new Locale("dutch"));
    private HerInschrijving heriInSchrijving;
    
    private SQLhandler SQLhandlr;
    /**
     * Creates new form AddLid
     */
    public AddLid(Main main) {
        initComponents();
        SQLhandlr = main.getSQLhandler();
        heriInSchrijving = new HerInschrijving(main, this);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("mercurius.png")));
        begin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voornaam = new javax.swing.JTextField();
        naam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwoord = new javax.swing.JPasswordField();
        rePaswoord = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        clubNaam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        actiefLid = new javax.swing.JRadioButton();
        pasiefLid = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercurius Add Lid");

        jLabel1.setText("Naam:");

        jLabel2.setText("Voornaam:");

        voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddLid.this.keyTyped(evt);
            }
        });

        naam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddLid.this.keyTyped(evt);
            }
        });

        jLabel3.setText("Passwoord:");

        passwoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddLid.this.keyTyped(evt);
            }
        });

        rePaswoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddLid.this.keyTyped(evt);
            }
        });

        jLabel4.setText("Re Pass:");

        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel5.setText("Club Naam:");

        jLabel6.setText("Email:");

        buttonGroup1.add(actiefLid);
        actiefLid.setText("Actief lid");
        actiefLid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pasiefLid);
        pasiefLid.setText("Pasief lid");
        pasiefLid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clubNaam)
                            .addComponent(voornaam)
                            .addComponent(naam)
                            .addComponent(passwoord)
                            .addComponent(rePaswoord)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actiefLid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pasiefLid)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePaswoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clubNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actiefLid)
                    .addComponent(pasiefLid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTyped
        if (!naam.getText().isEmpty() && !voornaam.getText().isEmpty()
                && !passwoord.getText().isEmpty() && !rePaswoord.getText().isEmpty()
                && !email.getText().isEmpty()
                && (actiefLid.isSelected() || pasiefLid.isSelected())) {
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_keyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            String sql = "SELECT * FROM leden WHERE lid_naam= '" + naam.getText() + "' AND lid_voornaam= '" + voornaam.getText() + "';";
            if(!passwoord.getText().equals(rePaswoord.getText())){
                JOptionPane.showMessageDialog(this, "De wachtwoorden komen niet overeen", "WARRNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            SQLhandlr.maakConnectie();
            ResultSet rs = SQLhandlr.voerQryUit(sql);
            rs.beforeFirst();
            if(rs.next()){
                heriInSchrijving.setVisible(true);
                heriInSchrijving.setValeus();
                heriInSchrijving.setid_Lid(rs.getInt("lid_id"));
                dispose();
            }else{
                System.out.println("lots.mercurius.addLid.AddLid.submitActionPerformed()"+" lid wordt weggeschreven");
                rs.moveToInsertRow();
                rs.updateString("lid_naam", naam.getText());
                rs.updateString("lid_voornaam", voornaam.getText());
                String pass = "";
                for (char c : passwoord.getPassword()){
                    pass += c;
                }
                rs.updateString("lid_passwoord", SQLhandlr.encrypt(pass));
                rs.updateDate("lid_jaar", new java.sql.Date(day.getTimeInMillis()));
                rs.updateInt("func_id", 0);
                rs.updateString("lid_email", email.getText());
                rs.updateString("Club_naam", clubNaam.getText());
                rs.updateBoolean("lid_actief", actiefLid.isSelected());
                rs.insertRow();
                rs.last();
                int id = rs.getInt("lid_id");
                rs.close();
                JOptionPane.showMessageDialog(this, "U bent succsessvol ingeschreven\nUw lid id = " + id, "SUCCSESS", JOptionPane.INFORMATION_MESSAGE);
                begin();
            }
            SQLhandlr.sluitConnectie();
        } catch (SQLException ex) {
            Logger.getLogger(AddLid.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        if (!naam.getText().isEmpty() && !voornaam.getText().isEmpty()
                && !passwoord.getText().isEmpty() && !rePaswoord.getText().isEmpty()
                && !email.getText().isEmpty()
                && (actiefLid.isSelected() || pasiefLid.isSelected())) {
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actiefLid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField clubNaam;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField naam;
    private javax.swing.JRadioButton pasiefLid;
    private javax.swing.JPasswordField passwoord;
    private javax.swing.JPasswordField rePaswoord;
    private javax.swing.JButton submit;
    private javax.swing.JTextField voornaam;
    // End of variables declaration//GEN-END:variables

    public boolean isActiefLid(){
        return actiefLid.isSelected();
    }
    
    public String getEmail(){
        return email.getText();
    }
    
    public String getVoorNaam(){
        return voornaam.getText();
    }
    
    public String getNaam(){
        return naam.getText();
    }
    
    public String getClubNaam(){
        return clubNaam.getText();
    }
    
    public void begin() {
        naam.setText("");
        voornaam.setText("");
        passwoord.setText("");
        rePaswoord.setText("");
        clubNaam.setText("");
        email.setText("");
        submit.setEnabled(false);
        actiefLid.setSelected(false);
        pasiefLid.setSelected(false);
    }
}
