/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lots.mercurius.addLid;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lots.mercurius.stemming.Main;
import lots.mercurius.stemming.sqlHandler.SQLhandler;

/**
 *
 * @author joris
 */
public class HerInschrijving extends javax.swing.JFrame {

    private Main main;
    private AddLid addLid;
    private SQLhandler SQLhandler;

    private Calendar day = Calendar.getInstance(TimeZone.getTimeZone("Europe/Brussels"), new Locale("dutch"));

    /**
     * Creates new form HerInschrijving
     */
    public HerInschrijving(Main main, AddLid addLid) {
        initComponents();
        this.main = main;
        this.addLid = addLid;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("mercurius.png")));
    }

    public void setValeus() {
        clubNaam.setText(addLid.getClubNaam());
        email.setText(addLid.getEmail());
        naam.setText(addLid.getNaam());
        voornaam.setText(addLid.getVoorNaam());
        actiefLid.setSelected(addLid.isActiefLid());
        pasiefLid.setSelected(!addLid.isActiefLid());
        SQLhandler = main.getSQLhandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        voornaam = new javax.swing.JTextField();
        naam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwoord = new javax.swing.JPasswordField();
        rePaswoord = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clubNaam = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        newPass = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        oldPasswoord = new javax.swing.JPasswordField();
        actiefLid = new javax.swing.JRadioButton();
        pasiefLid = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercurius Her In Schrijving");

        jLabel1.setText("Naam:");

        jLabel6.setText("Email:");

        jLabel2.setText("Voornaam:");

        voornaam.setEnabled(false);

        naam.setEnabled(false);

        jLabel3.setText("Passwoord:");

        passwoord.setEnabled(false);
        passwoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswoordKeyTyped(evt);
            }
        });

        rePaswoord.setEnabled(false);
        rePaswoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswoordKeyTyped(evt);
            }
        });

        jLabel4.setText("Re Pass:");

        jLabel5.setText("Club Naam:");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        newPass.setText("Verander Passwoord");
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });

        jLabel7.setText("Old Pass:");

        oldPasswoord.setEnabled(false);
        oldPasswoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswoordKeyTyped(evt);
            }
        });

        buttonGroup1.add(actiefLid);
        actiefLid.setText("Actief lid");
        actiefLid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pasiefLid);
        pasiefLid.setText("Pasief Lid");
        pasiefLid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(voornaam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actiefLid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(pasiefLid))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(clubNaam))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPass)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rePaswoord)
                            .addComponent(oldPasswoord)
                            .addComponent(passwoord))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clubNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actiefLid)
                    .addComponent(pasiefLid))
                .addGap(18, 18, 18)
                .addComponent(newPass)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(oldPasswoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePaswoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(submit)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        if (newPass.isSelected()) {
            passwoord.setEnabled(true);
            oldPasswoord.setEnabled(true);
            rePaswoord.setEnabled(true);
            submit.setEnabled(false);
        } else {
            passwoord.setEnabled(false);
            oldPasswoord.setEnabled(false);
            rePaswoord.setEnabled(false);
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_newPassActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            if (newPass.isSelected()) {
                try {
                    //herschrijf pass
                    if (!passwoord.getText().equals(rePaswoord.getText())) {
                        JOptionPane.showMessageDialog(this, "De Nieuwe wachtwoorden komen niet overeen");
                        return;
                    }
                    String sql = "SELECT * FROM leden WHERE lid_naam='" + naam.getText() + "' AND lid_voornaam='" + voornaam.getText() + "';";
                    SQLhandler.maakConnectie();
                    ResultSet rs = SQLhandler.voerQryUit(sql);
                    rs.beforeFirst();
                    rs.next();
                    String passDB = rs.getString("lid_passwoord");
                    String encript = "";
                    for (char c : oldPasswoord.getPassword()) {
                        encript += c;
                    }
                    String passING = SQLhandler.encrypt(encript);
                    if (!passING.equals(passDB)) {
                        JOptionPane.showMessageDialog(this, "Het oude wachtwoord is fout", "WARRNING", JOptionPane.WARNING_MESSAGE);
                        rs.close();
                        SQLhandler.sluitConnectie();
                        return;
                    }
                    rs.updateString("lid_passwoord", SQLhandler.encrypt(passwoord.getText()));
                    rs.updateRow();
                    rs.close();
                    SQLhandler.sluitConnectie();
                } catch (SQLException ex) {
                    Logger.getLogger(HerInschrijving.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String sql = "SELECT * FROM leden WHERE lid_naam='" + naam.getText() + "' AND lid_voornaam='" + voornaam.getText() + "';";
            SQLhandler.maakConnectie();
            ResultSet rs = SQLhandler.voerQryUit(sql);
            rs.beforeFirst();
            rs.next();
            rs.updateDate("lid_jaar", new java.sql.Date(day.getTimeInMillis()));
            rs.updateString("lid_email", email.getText());
            rs.updateString("Club_naam", clubNaam.getText());
            rs.updateBoolean("lid_actief", actiefLid.isSelected());
            rs.updateRow();
            rs.close();
            SQLhandler.sluitConnectie();
            //herschrij inschrijvings jaar
            //en eventueele andere aanpassingen
            JOptionPane.showMessageDialog(this, "U bent succsessvol ingeschreven", "SUCCSESS", JOptionPane.INFORMATION_MESSAGE);
            begin();
            dispose();
            addLid.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HerInschrijving.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void PasswoordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswoordKeyTyped
        if (!oldPasswoord.getText().isEmpty() && !passwoord.getText().isEmpty() && !rePaswoord.getText().isEmpty() && (pasiefLid.isSelected() || actiefLid.isSelected())) {
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_PasswoordKeyTyped

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        if ((pasiefLid.isSelected() || actiefLid.isSelected())) {
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actiefLid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField clubNaam;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField naam;
    private javax.swing.JCheckBox newPass;
    private javax.swing.JPasswordField oldPasswoord;
    private javax.swing.JRadioButton pasiefLid;
    private javax.swing.JPasswordField passwoord;
    private javax.swing.JPasswordField rePaswoord;
    private javax.swing.JButton submit;
    private javax.swing.JTextField voornaam;
    // End of variables declaration//GEN-END:variables

    public void begin() {
        clubNaam.setText("");
        email.setText("");
        newPass.setSelected(false);
        naam.setText("");
        voornaam.setText("");
        oldPasswoord.setText("");
        passwoord.setText("");
        rePaswoord.setText("");
        submit.setEnabled(true);
        actiefLid.setSelected(false);
        pasiefLid.setSelected(false);
        addLid.begin();
    }

}
