/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lots.mercurius.stemming.schermen;

import lots.mercurius.stemming.Main;

/**
 *
 * @author joris
 */
public class BeginScherm extends javax.swing.JPanel {

    private Main main;
    /**
     * Creates new form BeginScherm
     */
    public BeginScherm(Main main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        naam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        voornaam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwoord = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Mercurius Stemming"));

        jLabel1.setText("Naam:");

        naam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                naamKeyTyped(evt);
            }
        });

        jLabel2.setText("Voornaam:");

        voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                voornaamKeyTyped(evt);
            }
        });

        jLabel3.setText("Passwoord:");

        passwoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwoordKeyTyped(evt);
            }
        });

        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naam)
                            .addComponent(voornaam)
                            .addComponent(passwoord, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voornaamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voornaamKeyTyped
        checkIngevuld();
    }//GEN-LAST:event_voornaamKeyTyped

    private void naamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_naamKeyTyped
        checkIngevuld();
    }//GEN-LAST:event_naamKeyTyped

    private void passwoordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwoordKeyTyped
        checkIngevuld();
    }//GEN-LAST:event_passwoordKeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        main.userLogin(this);
    }//GEN-LAST:event_submitActionPerformed

    /**
     * retrunt de naam ingegeven
     * @return String naam
     */
    public String getNaam(){
        return naam.getText();
    }
    
    /**
     * retrunt de voornaam ingegeven
     * @return String naam
     */
    public String getVoornaam(){
        return voornaam.getText();
    }
    
    /**
     * returnd pass die is ingegeven
     * @return String pass
     */
    public String getPasswoord(){
        return passwoord.getText();
    }
    
    private void checkIngevuld(){
        //gaat checken of alle velden zijn ingevuld en dan zet die de submit buten anabled
        if(!naam.getText().isEmpty() && !voornaam.getText().isEmpty() && !passwoord.getText().isEmpty()){
            submit.setEnabled(true);
        }else{
            submit.setEnabled(false);
        }
    }
    
    /**
     * set het pannel terug naar begin waardes
     */
    public void begin(){
        naam.setText("");
        passwoord.setText("");
        submit.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField naam;
    private javax.swing.JPasswordField passwoord;
    private javax.swing.JButton submit;
    private javax.swing.JTextField voornaam;
    // End of variables declaration//GEN-END:variables
}
