/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lots.mercurius.voegOpkomendeToe;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import lots.mercurius.stemming.IngelogdPersoon;
import lots.mercurius.stemming.Main;
import lots.mercurius.stemming.sqlHandler.SQLhandler;

/**
 *
 * @author joris
 */
public class Login extends javax.swing.JFrame {
    
    private Main main;
    private VoegOpkomendeToe voegOpkomendeToe;

    /**
     * Creates new form Login
     */
    public Login(Main main) {
        initComponents();
        this.main = main;
        voegOpkomendeToe = new VoegOpkomendeToe(main, this);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("mercurius.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        voornaam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        naam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwoord = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercurius Log Voeg Opkomende Toe");

        jLabel1.setText("Voornaam:");

        voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        jLabel2.setText("Naam:");

        naam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        jLabel3.setText("Passwoord:");

        passwoord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voornaam)
                            .addComponent(naam)
                            .addComponent(passwoord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        SQLhandler sqlHanler = main.getSQLhandler();
        try {
            String sql
                    = "SELECT * FROM leden WHERE lid_naam= '" + naam.getText() + "' AND lid_voornaam= '" + voornaam.getText() + "';";
            sqlHanler.maakConnectie();
            IngelogdPersoon p = main.getIngelogdPersoon();
            ResultSet rs = sqlHanler.voerQryUit(sql);
            rs.beforeFirst();
            rs.next();
            String pass = rs.getString("lid_passwoord");
            p.setLid_id(rs.getInt("lid_id"));
            p.setNaam(rs.getString("lid_naam"));
            p.setVoornaam(rs.getString("lid_voornaam"));
            p.setFunc_id(rs.getInt("func_id"));
            rs.close();
            sqlHanler.sluitConnectie();
            sql
                    = "SELECT * FROM functie WHERE func_id= '" + p.getFunc_id() + "';";
            sqlHanler.maakConnectie();
            rs = sqlHanler.voerQryUit(sql);
            rs.beforeFirst();
            rs.next();
            p.setRechten(rs.getInt("func_rechten"));
            sqlHanler.sluitConnectie();
            if (pass.equals(sqlHanler.encrypt(passwoord.getText()))) {
                main.setIngelogPersoon(p);
                //WW ok
                //check voor rechten
                if(p.getRechten() >= 4){
                    //rchten ok
                    voegOpkomendeToe.setVisible(true);
                    dispose();
                    begin();
                }else{
                    JOptionPane.showMessageDialog(this, "U heeft geen rechten om een opkoomende toe te voeggen", "WARRNING", JOptionPane.WARNING_MESSAGE);
                    begin();
                }
            } else {
                //niet ok
                JOptionPane.showMessageDialog(this, "Foute login", "WARNNING", JOptionPane.WARNING_MESSAGE);
                begin();
            }
        } catch (SQLException ex) {
            return;
        }
    }//GEN-LAST:event_submitActionPerformed

    private void KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyTyped
        if(!naam.getText().isEmpty() && !voornaam.getText().isEmpty() && !passwoord.getText().isEmpty()){
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField naam;
    private javax.swing.JPasswordField passwoord;
    private javax.swing.JButton submit;
    private javax.swing.JTextField voornaam;
    // End of variables declaration//GEN-END:variables
    
    public void begin(){
        naam.setText("");
        voornaam.setText("");
        passwoord.setText("");
        submit.setEnabled(false);
        main.setIngelogPersoon(new IngelogdPersoon(main));
    }

}
