/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lots.mercurius.voegOpkomendeToe;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lots.mercurius.stemming.Main;
import lots.mercurius.stemming.sqlHandler.SQLhandler;

/**
 *
 * @author joris
 */
public class VoegOpkomendeToe extends javax.swing.JFrame {

    private Main main;
    private Login login;

    /**
     * Creates new form VoegOpkomendeToe
     */
    public VoegOpkomendeToe(Main main, Login login) {
        initComponents();
        this.main = main;
        this.login = login;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("mercurius.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voornaam = new javax.swing.JTextField();
        naam = new javax.swing.JTextField();
        functie = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercurius Nieuwe Opkomende");

        jLabel1.setText("naam:");

        jLabel2.setText("Voornaam:");

        voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        naam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTyped(evt);
            }
        });

        functie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Praeses", "Pro-Senior", "Pro-Senior Honorescousa" }));

        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(functie, 0, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voornaam)
                            .addComponent(naam)))
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(functie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyTyped
        if (!naam.getText().isEmpty() && !voornaam.getText().isEmpty()) {
            submit.setEnabled(true);
        }
    }//GEN-LAST:event_KeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            String sql = "SELECT * FROM functie WHERE func_naam='" + functie.getSelectedItem().toString() + "';";
            SQLhandler sqlHandler = main.getSQLhandler();
            sqlHandler.maakConnectie();
            ResultSet rs = sqlHandler.voerQryUit(sql);
            rs.beforeFirst();
            rs.next();
            int func_id = rs.getInt("func_id");
            rs.close();
            sqlHandler.sluitConnectie();
            
            
            sql = "SELECT * FROM leden WHERE lid_naam='" + naam.getText() + "' AND lid_voornaam='" + voornaam.getText() + "';";
            sqlHandler.maakConnectie();
            rs = sqlHandler.voerQryUit(sql);
            rs.beforeFirst();
            rs.next();
            int lid_id = rs.getInt("lid_id");
            rs.close();
            sqlHandler.sluitConnectie();
            
            
            sql = "SELECT * FROM komtop WHERE lid_id='" + lid_id + "' AND func_id='" + func_id + "';";
            sqlHandler.maakConnectie();
            rs = sqlHandler.voerQryUit(sql);
            rs.beforeFirst();
            if(rs.next()){
                //komt al op
                JOptionPane.showMessageDialog(this, "Deze persoon komt al op");
            }else{
                //moet worden weg geschreven
                rs.moveToInsertRow();
                rs.updateInt("func_id", func_id);
                rs.updateInt("lid_id", lid_id);
                rs.updateInt("stemmen_voor", 0);
                rs.updateInt("stemmen_tegen", 0);
                rs.insertRow();
            }
            rs.close();
            sqlHandler.sluitConnectie();
            JOptionPane.showMessageDialog(this, "Opkomende is toegeboegd", "SUCCSESS", JOptionPane.INFORMATION_MESSAGE);
            begin();
        } catch (SQLException ex) {
            Logger.getLogger(VoegOpkomendeToe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> functie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField naam;
    private javax.swing.JButton submit;
    private javax.swing.JTextField voornaam;
    // End of variables declaration//GEN-END:variables

    public void begin(){
        naam.setText("");
        voornaam.setText("");
        functie.setSelectedIndex(0);
        login.setVisible(true);
        dispose();
    }
    
}
